apiVersion: apps/v1
kind: Deployment

metadata: 
  name: app1
  namespace: gsk

spec:
  replicas: 2
  template:
    metadata:
      name: app1
      labels:
        client: "GSK_tech"
    spec: 
      containers:
      - name: app1
        image: httpd
  selector: 
    matchLabels:
      client: "GSK_tech"
