apiVersion: v1
kind: Service

metadata:
  name: app1-service
  namespace: gsk

spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30012
  - name: https
    protocol: TCP
    port: 443
    nodePort: 30013
  externalIPs:
  - 123.45.67.89
  - 123.45.67.89 
  selector:
    client: "GSK_tech"
  
