apiVersion: v1
kind: Service

metadata:
  name: app1service
  namespace: gsk

spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30012 
  selector:
    client: "GSK_tech"
  
